version: '3.8'

services:
  backend:
    build:
      context: ./cinema
      dockerfile: Dockerfile
    container_name: cinema-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/cinema
      - SPRING_DATASOURCE_USERNAME=yourusername
      - SPRING_DATASOURCE_PASSWORD=yourpassword
    depends_on:
      - database

  frontend:
    build:
      context: ./cinema-frontend
      dockerfile: Dockerfile
    container_name: cinema-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  database:
    image: postgres:13
    container_name: cinema-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cinema
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
